use proper gradlew command if path is set to gradlew (#50)
* use proper gradlew command if path is set to gradlew

* Fix _tmp file path

* Recreate _tmp directory

* Use absoulte path for gradle build file

* Don't set GradleFile to absolute path if empty

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -6,6 +6,8 @@ app:
   - RELEASE_VERSION: 1.8.0
   # define these here, or in your .bitrise.secrets.yml (if required)
   - ANDROID_HOME: $ANDROID_HOME
+  - ORIG_BITRISE_SOURCE_DIR: $BITRISE_SOURCE_DIR
+  - BRANCH: master
 
 workflows:
 
@@ -23,7 +25,7 @@ workflows:
   test:
     description: "CI workflow - this should always pass!"
     envs:
-    - SAMPLE_APP_GIT_CLONE_URL: https://github.com/bitrise-samples/sample-apps-android-sdk22.git
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-android-sdk22.git
     - GRADLE_FILE: ./build.gradle
     - GRADLE_TASK: assembleDebug
     - GRADLEW_PATH: ./gradlew
@@ -32,9 +34,21 @@ workflows:
     after_run:
     - _common
 
+  test-gradlew-path:
+    description: "CI workflow - this should always pass!"
+    envs:
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-android-sdk22.git
+    - GRADLE_FILE: ./build.gradle
+    - GRADLE_TASK: assembleDebug
+    - GRADLEW_PATH: gradlew
+    - APK_FILE_EXCLUDE_FILTER: "*-unaligned.apk"
+    - MAPPING_FILE_INCLUDE_FILTER: "*/release/mapping.txt"
+    after_run:
+    - _common
+
   test-multiple-tasks:
     envs:
-    - SAMPLE_APP_GIT_CLONE_URL: https://github.com/bitrise-samples/sample-apps-android-sdk22.git
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-android-sdk22.git
     - GRADLE_FILE: ./build.gradle
     - GRADLE_TASK: assembleDebug assembleRelease
     - GRADLEW_PATH: ./gradlew
@@ -45,7 +59,7 @@ workflows:
   
   test-subdir:
     envs:
-    - SAMPLE_APP_GIT_CLONE_URL: https://github.com/bitrise-samples/sample-apps-android-sdk22-subdir.git
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-android-sdk22-subdir.git
     - GRADLE_FILE: ./src/build.gradle
     - GRADLE_TASK: assembleDebug
     - GRADLEW_PATH: ./src/gradlew
@@ -56,7 +70,7 @@ workflows:
 
   test-no-gradlew-error:
     envs:
-    - SAMPLE_APP_GIT_CLONE_URL: https://github.com/bitrise-samples/android-sdk22-no-gradlew.git
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/android-sdk22-no-gradlew.git
     - GRADLE_FILE: ./build.gradle
     - GRADLE_TASK: assembleDebug
     - GRADLEW_PATH: ""
@@ -67,7 +81,7 @@ workflows:
 
   test-no-root-buildfile:
     envs:
-    - SAMPLE_APP_GIT_CLONE_URL: https://github.com/bitrise-samples/android-empty-library.git
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/android-empty-library.git
     - GRADLE_FILE: ""
     - GRADLE_TASK: assembleDebug
     - GRADLEW_PATH: "./gradlew"
@@ -78,7 +92,7 @@ workflows:
 
   test-apk-split:
     envs:
-    - SAMPLE_APP_GIT_CLONE_URL: https://github.com/bitrise-samples/sample-apps-android-abi-split.git
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-android-abi-split.git
     - GRADLE_FILE: ""
     - GRADLE_TASK: assembleDebug
     - GRADLEW_PATH: "./gradlew"
@@ -90,30 +104,33 @@ workflows:
   _common:
     steps:
     - script:
+        title: recreate _tmp directory
         inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-            rm -rf ./_tmp
-    - git-clone:
-        run_if: true
-        inputs:
-        - repository_url: $SAMPLE_APP_GIT_CLONE_URL
-        - branch: master
-        - commit: ""
-        - tag: ""
-        - pull_request_id: ""
-        - clone_into_dir: ./_tmp/sample-app-repo
+        - content: rm -rf "$ORIG_BITRISE_SOURCE_DIR/_tmp" && mkdir "$ORIG_BITRISE_SOURCE_DIR/_tmp"
     - change-workdir:
-        title: Switch working dir to test/_tmp dir
+        title: Switch working dir to _tmp dir
         description: |-
           To prevent step testing issues, like referencing relative
           files with just './some-file', which would work for local tests
           but not if the step is included in another bitrise.yml!
         run_if: true
         inputs:
-        - path: ./_tmp/sample-app-repo
-        - is_create_path: true
+        - path: "$ORIG_BITRISE_SOURCE_DIR/_tmp"
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            if [[ -z "${SAMPLE_APP_URL}" ]]; then
+              echo "error: there is no SAMPLE_APP_URL env var specified"
+              exit 1
+            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
+              echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
+              exit 1
+            fi
+            git init
+            git remote add origin "${SAMPLE_APP_URL}"
+            git fetch || exit 1
+            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
     - path::./:
         inputs:
         - gradle_file: $GRADLE_FILE
