Fix Output checks

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -152,6 +152,7 @@ workflows:
       - _check_cache
       - _check_output_apk
 
+  # Ouptuts an *.aar
   test_no_root_buildfile:
     envs:
       - TEST_APP_URL: https://github.com/bitrise-samples/android-empty-library.git
@@ -163,7 +164,6 @@ workflows:
       - GRADLE_OPTIONS: ""
     after_run:
       - _common
-      - _check_output_apk
 
   test_apk_split:
     envs:
@@ -248,11 +248,12 @@ workflows:
           is_always_run: true
           inputs:
             - content: |-
-                if [ ! -f $BITRISE_AAB_PATH ]; then
-                  echo "AAB bundle not found at ${BITRISE_AAB_PATH}"
+                set -e
+                if [ ! -f "$BITRISE_AAB_PATH" ]; then
+                  echo "AAB bundle not found at '${BITRISE_AAB_PATH}'"
                   exit 1
                 fi
-                echo "AAB bundle found at ${BITRISE_AAB_PATH}"
+                echo "AAB bundle found at '${BITRISE_AAB_PATH}'"
 
   _check_output_apk:
     steps:
@@ -261,11 +262,12 @@ workflows:
           is_always_run: true
           inputs:
             - content: |-
-                if [ ! -f $BITRISE_APK_PATH ]; then
-                  echo "APK not found at ${BITRISE_APK_PATH}"
+                set -e
+                if [ ! -f "$BITRISE_APK_PATH" ]; then
+                  echo "APK not found at '${BITRISE_APK_PATH}'"
                   exit 1
                 fi
-                echo "APK found at ${BITRISE_APK_PATH}"
+                echo "APK found at '${BITRISE_APK_PATH}'"
 
   _check_log_output:
     steps:
@@ -279,7 +281,7 @@ workflows:
                   exit 1
                 fi
 
-                if [ ! -f $BITRISE_GRADLE_RAW_RESULT_TEXT_PATH ]; then
+                if [ ! -f "$BITRISE_GRADLE_RAW_RESULT_TEXT_PATH" ]; then
                     echo "Log file not found at ${BITRISE_GRADLE_RAW_RESULT_TEXT_PATH}"
                     exit 1
                 fi
@@ -294,11 +296,11 @@ workflows:
           is_always_run: true
           inputs:
             - content: |-
-                if [[ -z "${BITRISE_CACHE_INCLUDE_PATHS}" ]]; then
+                if [ -z "${BITRISE_CACHE_INCLUDE_PATHS}" ]; then
                   echo "Include paths (BITRISE_CACHE_INCLUDE_PATHS) are not set"
                   exit 1
                 fi
-                if [[ -z "${BITRISE_CACHE_EXCLUDE_PATHS}" ]]; then
+                if [ -z "${BITRISE_CACHE_EXCLUDE_PATHS}" ]; then
                   echo "Exclude paths (BITRISE_CACHE_EXCLUDE_PATHS) are not set"
                   exit 1
                 fi
